---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - acceptance/**/*
    - vendor/**/*

require:
  - rubocop-performance
  - rubocop-rspec

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'spec/mocks/win32.rb'

Naming/MethodName:
  Exclude:
    - 'spec/mocks/win32ole.rb'
    - 'spec/mocks/ffi.rb'

Naming/VariableNumber:
  Exclude:
    - 'lib/facter/resolvers/windows/ffi/networking_ffi.rb'
    - 'lib/facter/util/facts/windows_release_finder.rb'

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
